const DAY=document.body.dataset.day||'5';
const DATE=document.body.dataset.date||'2026-09-04';
const KEY=`cultura365-dia${DAY}-v1`;
const GLOBAL_KEY='cultura365-global-v1';
const state=JSON.parse(localStorage.getItem(KEY)||'{}');
const globalState=JSON.parse(localStorage.getItem(GLOBAL_KEY)||'{}');
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const saveGlobal=()=>localStorage.setItem(GLOBAL_KEY,JSON.stringify(globalState));

const toast=(msg)=>{let t=document.getElementById('toast');if(!t){t=document.createElement('div');t.id='toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(window.__c365toast);window.__c365toast=setTimeout(()=>t.classList.remove('show'),2200)};
const esc=s=>(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const norm=s=>(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();

const patch=document.createElement('style');
patch.textContent=`
.mode-help,.progress-card{max-width:900px;margin:14px auto 24px;padding:18px 20px;background:var(--paper);border:1px solid var(--line);border-radius:16px;box-shadow:var(--shadow)}
.mode-help strong{color:var(--forest)}.mode-help p{margin:5px 0;color:var(--muted);font-size:14px}.mode-status{color:var(--ink)!important;font-weight:800;margin-top:10px!important}
.progress-card{background:linear-gradient(135deg,var(--paper),var(--sage))}.progress-card-top{display:flex;justify-content:space-between;gap:14px;align-items:end}.progress-card strong{font:800 28px Georgia,serif}.progress-track{height:12px;background:var(--line);border-radius:99px;overflow:hidden;margin:12px 0 8px}.progress-fill{height:100%;width:0;background:var(--gold);transition:.25s}.progress-card small{color:var(--muted)}
.continue-btn{border:0;background:var(--forest);color:#fff;border-radius:10px;padding:10px 14px;font-weight:750;cursor:pointer;margin-left:10px}.chapter-tools{display:flex;gap:8px;justify-content:flex-end;margin:-4px 0 12px}.chapter-tools button{border:1px solid var(--line);background:var(--bg);color:var(--ink);border-radius:999px;padding:7px 11px;cursor:pointer;font-size:12px}.chapter-tools button.saved{background:var(--sage);border-color:var(--forest)}.note-box{display:none;margin:8px 0 18px;padding:12px;background:var(--sage);border-radius:12px}.note-box.open{display:block}.note-box textarea{min-height:86px}.note-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:8px}.note-actions button{border:0;background:var(--forest);color:white;border-radius:8px;padding:8px 11px;cursor:pointer}
.learning-btn{position:fixed;left:18px;bottom:18px;z-index:89;border:0;border-radius:999px;background:var(--gold);color:#17201f;padding:12px 15px;font-weight:850;box-shadow:var(--shadow);cursor:pointer}.learning-btn span{margin-left:5px}.learning-overlay{display:none;position:fixed;inset:0;background:rgba(0,0,0,.32);z-index:90}.learning-overlay.open{display:block}.learning-panel{position:fixed;top:0;right:-470px;width:min(440px,94vw);height:100dvh;background:var(--paper);z-index:91;box-shadow:-18px 0 50px rgba(0,0,0,.2);transition:.28s;overflow:auto;padding:22px}.learning-panel.open{right:0}.learning-head{display:flex;justify-content:space-between;align-items:center;position:sticky;top:-22px;background:var(--paper);padding:18px 0 12px;z-index:2;border-bottom:1px solid var(--line)}.learning-head h2{font:800 30px Georgia,serif;margin:0}.learning-close{border:1px solid var(--line);background:var(--bg);color:var(--ink);border-radius:50%;width:38px;height:38px;cursor:pointer}.learn-section{padding:18px 0;border-bottom:1px solid var(--line)}.learn-section h3{font:700 20px Georgia,serif;margin:0 0 10px}.learn-search{width:100%;padding:12px;border:1px solid var(--line);border-radius:10px;background:var(--bg);color:var(--ink);font:inherit}.search-results{margin-top:9px}.search-hit,.saved-hit{display:block;width:100%;text-align:left;border:0;background:var(--sage);color:var(--ink);border-radius:9px;padding:10px;margin:6px 0;cursor:pointer}.stat-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.stat-grid div{background:var(--sage);border-radius:10px;padding:10px}.stat-grid b,.stat-grid span{display:block}.stat-grid b{font:800 20px Georgia,serif}.stat-grid span{font-size:11px;color:var(--muted)}.concept-list button{border:1px solid var(--line);background:var(--bg);color:var(--ink);border-radius:999px;padding:7px 10px;margin:3px;cursor:pointer}.concept-def{background:var(--sage);padding:10px;border-radius:9px;margin-top:8px;font-size:14px}.route-mini{padding:9px 0}.route-mini b,.route-mini span{display:block}.route-mini span{font-size:13px;color:var(--muted)}.archive-link{display:block;padding:10px;border-radius:9px;background:var(--sage);color:var(--ink);text-decoration:none;margin:6px 0}.weekly-note{font-size:13px;color:var(--muted)}
@media(max-width:700px){.progress-card-top{align-items:flex-start;flex-direction:column}.continue-btn{margin:8px 0 0}.learning-btn span{display:none}.stat-grid{grid-template-columns:1fr 1fr}.learning-panel{padding:18px}}
`;
document.head.appendChild(patch);

const modes=document.querySelector('.reading-modes');
if(modes&&!document.querySelector('.mode-help')){
  const help=document.createElement('section');help.className='mode-help';help.innerHTML=`<strong>Cómo usar los modos</strong><p><b>Completo:</b> muestra toda la revista; las ampliaciones quedan cerradas.</p><p><b>Esencial:</b> deja solo el núcleo del día para una lectura breve.</p><p><b>Profundizar:</b> muestra toda la revista y abre automáticamente todos los apartados opcionales.</p><p class="mode-status" id="modeStatus">Modo actual: Completo.</p>`;modes.insertAdjacentElement('afterend',help);
  const pc=document.createElement('section');pc.className='progress-card';pc.innerHTML=`<div class="progress-card-top"><div><small>PROGRESO DE HOY</small><strong id="progressLarge">0 %</strong></div><div><span id="progressDetail">0 de 0 capítulos recorridos</span><button class="continue-btn" id="continueReading">Seguir leyendo →</button></div></div><div class="progress-track"><div id="progressFillLarge" class="progress-fill"></div></div><small>Un capítulo se marca cuando has avanzado aproximadamente por el 78 % de su altura. Es una estimación de recorrido, no una nota.</small>`;help.insertAdjacentElement('afterend',pc);
}
function setMode(mode){
  document.body.classList.remove('mode-essential','mode-deep');
  if(mode==='essential')document.body.classList.add('mode-essential');
  if(mode==='deep')document.body.classList.add('mode-deep');
  document.querySelectorAll('.mode').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));
  document.querySelectorAll('details.deep').forEach(d=>{d.open=mode==='deep'});
  const labels={all:'Completo — toda la revista.',essential:'Esencial — solo el núcleo.',deep:'Profundizar — revista completa + ampliaciones abiertas.'};
  const s=document.getElementById('modeStatus');if(s)s.textContent='Modo actual: '+labels[mode];
  state.mode=mode;save();setTimeout(updateProgress,60);toast(labels[mode]);
}
document.querySelectorAll('.mode').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));

const themeBtn=document.getElementById('themeBtn');if(themeBtn)themeBtn.addEventListener('click',()=>{document.body.classList.toggle('dark');state.dark=document.body.classList.contains('dark');save()});if(state.dark)document.body.classList.add('dark');
const topBtn=document.getElementById('toTop');if(topBtn)topBtn.addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}));

function visibleTracks(){return[...document.querySelectorAll('.track')].filter(el=>getComputedStyle(el).display!=='none')}
function trackKey(el,i){return el.id||el.dataset.key||('track-'+i)}
function markByScroll(){
  const tracks=visibleTracks();state.read=state.read||{};
  tracks.forEach((el,i)=>{const r=el.getBoundingClientRect(),key=trackKey(el,i),top=window.scrollY+r.top,threshold=top+Math.max(130,el.offsetHeight*.78),cursor=window.scrollY+window.innerHeight*.72;if(cursor>=threshold){state.read[key]=true;globalState.lastSection={date:DATE,key}}});
  save();saveGlobal();updateProgress();
}
function updateProgress(){
  const tracks=visibleTracks();let done=0;tracks.forEach((el,i)=>{if(state.read?.[trackKey(el,i)])done++});const pct=tracks.length?Math.min(100,Math.round(done/tracks.length*100)):0;
  const bar=document.getElementById('progressBar');if(bar)bar.style.width=pct+'%';const txt=document.getElementById('progressText');if(txt)txt.textContent=pct+'% leído';const large=document.getElementById('progressLarge');if(large)large.textContent=pct+' %';const fill=document.getElementById('progressFillLarge');if(fill)fill.style.width=pct+'%';const det=document.getElementById('progressDetail');if(det)det.textContent=`${done} de ${tracks.length} capítulos recorridos`;
  globalState.days=globalState.days||{};globalState.days[DATE]={...(globalState.days[DATE]||{}),day:DAY,pct,done,total:tracks.length,updated:new Date().toISOString()};saveGlobal();updateLearningCenterStats();
}
window.addEventListener('scroll',markByScroll,{passive:true});window.addEventListener('resize',updateProgress,{passive:true});

document.addEventListener('click',e=>{if(e.target?.id==='continueReading'){const tracks=visibleTracks();const pending=tracks.find((el,i)=>!state.read?.[trackKey(el,i)]);(pending||document.getElementById('memoria')||document.body).scrollIntoView({behavior:'smooth',block:'start'})}});

function paint(q,choice,answer){q.querySelectorAll('[data-choice]').forEach(btn=>{btn.classList.remove('correct','wrong');if(btn.dataset.choice===choice)btn.classList.add(choice===answer?'correct':'wrong')});const f=q.querySelector('.feedback');if(!f)return;if(choice===answer){f.textContent='Correcto. Este concepto gana estabilidad.';f.className='feedback good'}else{f.textContent='Revisar. Este concepto deberá reaparecer antes.';f.className='feedback bad'}}
document.querySelectorAll('.q[data-answer]').forEach(q=>{const k=q.dataset.key,a=q.dataset.answer;if(state[k])paint(q,state[k],a);q.querySelectorAll('[data-choice]').forEach(btn=>btn.addEventListener('click',()=>{state[k]=btn.dataset.choice;save();paint(q,state[k],a);updateQuizSummary()}))});
document.querySelectorAll('.open-q').forEach(q=>{const k=q.dataset.key,ta=q.querySelector('textarea'),btn=q.querySelector('.save-open');if(state[k])ta.value=state[k];btn?.addEventListener('click',()=>{state[k]=ta.value.trim();save();const f=q.querySelector('.feedback');if(f){f.textContent=state[k]?'Guardado en este dispositivo.':'Escribe algo antes de guardar.';f.className=state[k]?'feedback good':'feedback bad'}updateQuizSummary()})});
function updateQuizSummary(){let correct=0,answered=0,total=0;document.querySelectorAll('.q[data-answer]').forEach(q=>{total++;const v=state[q.dataset.key];if(v){answered++;if(v===q.dataset.answer)correct++}});const s=document.getElementById('quizScore');if(s)s.textContent=`${correct}/${total} correctos`;const qs=document.getElementById('quizState');if(qs)qs.textContent=answered===total?'Cerrados completados':'En progreso';globalState.days=globalState.days||{};globalState.days[DATE]={...(globalState.days[DATE]||{}),quiz:{correct,answered,total}};saveGlobal();updateLearningCenterStats()}
const reset=document.getElementById('resetQuiz');if(reset)reset.addEventListener('click',()=>{document.querySelectorAll('.q[data-key],.open-q[data-key]').forEach(q=>delete state[q.dataset.key]);save();location.reload()});
const copy=document.getElementById('copySummary');if(copy)copy.addEventListener('click',async()=>{const lines=[`CULTURA365_RESULTADOS DIA${DAY} ${DATE}`];let correct=0,total=0;document.querySelectorAll('.q[data-answer]').forEach(q=>{total++;const v=state[q.dataset.key]||'-',ok=v===q.dataset.answer;if(ok)correct++;lines.push(`${q.dataset.key}:${v}:${ok?'OK':'REVISAR'}`)});document.querySelectorAll('.open-q').forEach(q=>lines.push(`${q.dataset.key}:${(state[q.dataset.key]||'SIN_RESPUESTA').replace(/\s+/g,' ').slice(0,300)}`));const p=globalState.days?.[DATE]?.pct||0;lines.push(`LECTURA:${p}%`);lines.push(`CERRADAS:${correct}/${total}`);try{await navigator.clipboard.writeText(lines.join('\n'));toast('Resumen copiado. Pégalo en ChatGPT.')}catch{toast('No pude copiar automáticamente.')}});

globalState.favorites=globalState.favorites||{};globalState.notes=globalState.notes||{};
function chapterTitle(el){return el.querySelector('h2,h3')?.textContent.trim()||el.id||'Sección'}
function enhanceChapters(){document.querySelectorAll('.story.track').forEach(el=>{if(!el.id||el.querySelector('.chapter-tools'))return;const title=chapterTitle(el),id=el.id,key=`${DATE}:${id}`;const tools=document.createElement('div');tools.className='chapter-tools';const fav=document.createElement('button');fav.textContent=globalState.favorites[key]?'★ Guardado':'☆ Guardar';fav.classList.toggle('saved',!!globalState.favorites[key]);const note=document.createElement('button');note.textContent=globalState.notes[key]?'📝 Nota ✓':'📝 Nota';tools.append(fav,note);const nb=document.createElement('div');nb.className='note-box';nb.innerHTML=`<textarea placeholder="Escribe una idea, duda o conexión personal...">${esc(globalState.notes[key]?.text||'')}</textarea><div class="note-actions"><button class="save-note">Guardar nota</button></div>`;el.insertBefore(tools,el.children[1]||null);tools.insertAdjacentElement('afterend',nb);fav.addEventListener('click',()=>{if(globalState.favorites[key])delete globalState.favorites[key];else globalState.favorites[key]={date:DATE,day:DAY,id,title,url:`#${id}`};saveGlobal();fav.textContent=globalState.favorites[key]?'★ Guardado':'☆ Guardar';fav.classList.toggle('saved',!!globalState.favorites[key]);renderSaved();updateLearningCenterStats()});note.addEventListener('click',()=>nb.classList.toggle('open'));nb.querySelector('.save-note').addEventListener('click',()=>{const text=nb.querySelector('textarea').value.trim();if(text)globalState.notes[key]={date:DATE,day:DAY,id,title,text};else delete globalState.notes[key];saveGlobal();note.textContent=text?'📝 Nota ✓':'📝 Nota';toast(text?'Nota guardada':'Nota eliminada');renderSaved();updateLearningCenterStats()})})}

const overlay=document.createElement('div');overlay.className='learning-overlay';document.body.appendChild(overlay);
const panel=document.createElement('aside');panel.className='learning-panel';panel.innerHTML=`<div class="learning-head"><h2>Mi aprendizaje</h2><button class="learning-close" aria-label="Cerrar">×</button></div>
<div class="learn-section"><h3>Buscar en la edición</h3><input id="learnSearch" class="learn-search" placeholder="Roma, sudor, subducción, blues…"><div id="searchResults" class="search-results"></div></div>
<div class="learn-section"><h3>Hoy</h3><div class="stat-grid"><div><b id="statProgress">0%</b><span>lectura</span></div><div><b id="statQuiz">0/0</b><span>checkpoints</span></div><div><b id="statSaved">0</b><span>guardados</span></div></div></div>
<div class="learn-section"><h3>Biblioteca de conceptos</h3><div id="conceptList" class="concept-list"></div><div id="conceptDef"></div></div>
<div class="learn-section"><h3>Favoritos</h3><div id="favoriteList"></div></div>
<div class="learn-section"><h3>Notas personales</h3><div id="noteList"></div></div>
<div class="learn-section"><h3>Rutas activas</h3><div class="route-mini"><b>🏛 Roma · 5/30</b><span>Decenviros → apertura plebeya</span></div><div class="route-mini"><b>🎵 Música · Blues 2/20</b><span>Boogie/shuffle → R&amp;B</span></div><div class="route-mini"><b>🌏 Geografía · 5/30</b><span>Japón tectónico → corredor Tōkaidō</span></div><div class="route-mini"><b>📷 Fotografía · 5/30</b><span>Dirección de luz → balance de blancos</span></div><div class="route-mini"><b>🧠 Pensamiento crítico · 5/30</b><span>Confusión → selección/colisionadores</span></div><div class="route-mini"><b>👨‍👩‍👧 Crianza · 5/30</b><span>Instrucciones → transiciones</span></div></div>
<div class="learn-section"><h3>Archivo</h3><a class="archive-link" href="archivo/2026-09-03/">Día 4 · 3 septiembre</a><a class="archive-link" href="archivo/2026-09-02/">Día 3 · 2 septiembre</a><a class="archive-link" href="archivo/">Ver archivo completo →</a></div>
<div class="learn-section"><h3>Resumen semanal local</h3><div id="weeklySummary" class="weekly-note"></div></div>`;document.body.appendChild(panel);
const learningBtn=document.getElementById('learningBtn');function openLearning(){panel.classList.add('open');overlay.classList.add('open');renderSaved();updateLearningCenterStats()}function closeLearning(){panel.classList.remove('open');overlay.classList.remove('open')}learningBtn?.addEventListener('click',openLearning);overlay.addEventListener('click',closeLearning);panel.querySelector('.learning-close').addEventListener('click',closeLearning);

const searchable=[...document.querySelectorAll('.story, .routes-grid article')].filter(el=>el.id);const search=document.getElementById('learnSearch');search.addEventListener('input',()=>{const q=norm(search.value.trim()),box=document.getElementById('searchResults');if(q.length<2){box.innerHTML='';return}const hits=searchable.filter(el=>norm(el.textContent).includes(q)).slice(0,8);box.innerHTML=hits.length?hits.map(el=>`<button class="search-hit" data-go="${el.id}">${esc(chapterTitle(el))}</button>`).join(''):'<small>Sin coincidencias en esta edición.</small>';box.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>{closeLearning();document.getElementById(b.dataset.go)?.scrollIntoView({behavior:'smooth',block:'start'})}))});

const concepts={
  'Subducción':['geografia','Proceso por el que una placa litosférica se introduce bajo otra y desciende hacia el manto.'],
  'Calor latente':['ciencia','Energía absorbida o liberada durante un cambio de fase sin que el cambio se reduzca a subir o bajar temperatura.'],
  'Confusión':['riesgo','Distorsión de una asociación porque una tercera variable se relaciona causalmente con exposición y resultado.'],
  'Open weight':['tecnologia','Modelo cuyos pesos entrenados pueden descargarse, aunque eso no implica que datos y proceso de entrenamiento sean completamente abiertos.'],
  'Rest defence':['futbol','Estructura que un equipo mantiene durante su ataque para estar preparado ante una pérdida y el contraataque rival.'],
  'Boogie-woogie':['musica','Estilo pianístico afroamericano ligado al blues, con patrones repetitivos de bajo y fuerte impulso rítmico.'],
  'Decenviros':['roma','Comisión de diez magistrados asociada tradicionalmente a la redacción de las XII Tablas y a una posterior crisis de poder.']
};
const conceptList=document.getElementById('conceptList');conceptList.innerHTML=Object.keys(concepts).map(k=>`<button data-concept="${esc(k)}">${esc(k)}</button>`).join('');conceptList.querySelectorAll('[data-concept]').forEach(b=>b.addEventListener('click',()=>{const [id,def]=concepts[b.dataset.concept];document.getElementById('conceptDef').innerHTML=`<div class="concept-def"><b>${esc(b.dataset.concept)}</b><br>${esc(def)}<br><button class="search-hit" data-jump="${id}">Ir al tema →</button></div>`;document.querySelector('[data-jump]')?.addEventListener('click',e=>{closeLearning();document.getElementById(e.currentTarget.dataset.jump)?.scrollIntoView({behavior:'smooth'})})}));

function renderSaved(){const favs=Object.values(globalState.favorites||{}).sort((a,b)=>b.date.localeCompare(a.date));const notes=Object.values(globalState.notes||{}).sort((a,b)=>b.date.localeCompare(a.date));const fl=document.getElementById('favoriteList'),nl=document.getElementById('noteList');if(fl)fl.innerHTML=favs.length?favs.slice(0,10).map(x=>`<button class="saved-hit" data-local="${x.date===DATE?x.id:''}">★ ${esc(x.title)} <small>· Día ${esc(String(x.day))}</small></button>`).join(''):'<small>Aún no has guardado capítulos.</small>';if(nl)nl.innerHTML=notes.length?notes.slice(0,10).map(x=>`<button class="saved-hit" data-local="${x.date===DATE?x.id:''}">📝 ${esc(x.title)}<br><small>${esc(x.text.slice(0,90))}</small></button>`).join(''):'<small>Aún no has escrito notas.</small>';panel.querySelectorAll('.saved-hit[data-local]').forEach(b=>{if(b.dataset.local)b.addEventListener('click',()=>{closeLearning();document.getElementById(b.dataset.local)?.scrollIntoView({behavior:'smooth'})})})}
function updateLearningCenterStats(){if(!panel)return;const d=globalState.days?.[DATE]||{},q=d.quiz||{};const p=document.getElementById('statProgress'),qs=document.getElementById('statQuiz'),sv=document.getElementById('statSaved');if(p)p.textContent=(d.pct||0)+'%';if(qs)qs.textContent=`${q.correct||0}/${q.total||0}`;if(sv)sv.textContent=Object.keys(globalState.favorites||{}).length;const ws=document.getElementById('weeklySummary');if(ws){const days=Object.values(globalState.days||{}).filter(x=>x&&typeof x.pct==='number');if(days.length<3){ws.textContent='Todavía hay pocos días registrados en este navegador para una comparación semanal fiable.'}else{const avg=Math.round(days.reduce((a,x)=>a+x.pct,0)/days.length);const quizzes=days.map(x=>x.quiz).filter(Boolean);const correct=quizzes.reduce((a,x)=>a+(x.correct||0),0),total=quizzes.reduce((a,x)=>a+(x.total||0),0);ws.textContent=`${days.length} días registrados · lectura media ${avg}%${total?` · checkpoints ${correct}/${total}`:''}. El resumen semanal seguirá ganando utilidad conforme acumules días.`}}}

enhanceChapters();setMode(state.mode||'all');updateQuizSummary();markByScroll();renderSaved();updateLearningCenterStats();

/* Mejora editorial Día 5: menos manual, más revista visual */
const editorialStyle=document.createElement('style');editorialStyle.textContent=`
.editorial-compass{max-width:1080px;margin:22px auto 34px;display:grid;grid-template-columns:1.4fr 1fr;gap:16px}.editorial-lead,.editorial-picks{background:var(--paper);border:1px solid var(--line);border-radius:20px;padding:26px;box-shadow:var(--shadow)}.editorial-lead{background:linear-gradient(135deg,color-mix(in srgb,var(--paper) 86%,var(--sage)),var(--paper))}.editorial-lead .eyebrow{font-size:11px;letter-spacing:.14em;font-weight:900;color:var(--gold)}.editorial-lead h2{font:800 38px/1.05 Georgia,serif;margin:8px 0 12px}.editorial-lead p{margin:0 0 16px;color:var(--muted);font-size:17px}.editorial-lead a,.editorial-picks a{color:var(--forest);font-weight:800;text-decoration:none}.editorial-picks h3{font:700 22px Georgia,serif;margin:0 0 10px}.editorial-picks a{display:block;padding:9px 0;border-top:1px solid var(--line)}.editorial-picks a:first-of-type{border-top:0}.geo-visual{margin:22px 0 24px}.geo-visual img{width:100%;max-height:560px;object-fit:contain;border-radius:14px;background:#eef2ef;border:1px solid var(--line)}.geo-visual figcaption{font-size:12px;color:var(--muted);margin-top:7px}.look-first{margin:18px 0;padding:16px 18px;border-radius:14px;background:var(--sage);border-left:4px solid var(--gold)}.look-first b{display:block;margin-bottom:4px}.story#efemeride{max-width:1040px;border-top:7px solid var(--gold)}.story#geografia{max-width:1040px}.story#arte,.story#musica{max-width:980px}.story#crianza{max-width:980px}.story h3{scroll-margin-top:130px}@media(max-width:760px){.editorial-compass{grid-template-columns:1fr}.editorial-lead h2{font-size:31px}.editorial-lead,.editorial-picks{padding:20px}.geo-visual img{max-height:420px}}
`;document.head.appendChild(editorialStyle);
const highlights=document.querySelector('.highlights');if(highlights&&!document.querySelector('.editorial-compass')){const box=document.createElement('section');box.className='editorial-compass';box.innerHTML=`<article class="editorial-lead"><span class="eyebrow">HISTORIA CENTRAL · 12–15 MIN</span><h2>476: el día que “cayó Roma”… y por qué esa frase engaña</h2><p>Empieza aquí. No memorices solo una fecha: sigue qué instituciones sobreviven, quién sigue llamándose romano y por qué una transición de siglos acabó comprimida en un día.</p><a href="#efemeride">Entrar en la historia →</a></article><aside class="editorial-picks"><h3>Si hoy solo eliges tres</h3><a href="#geografia">🗺️ Mira el mapa tectónico de Japón antes de leer</a><a href="#musica">🎧 Escucha primero; explica después: blues y boogie</a><a href="#crianza">👨‍👩‍👧 Una herramienta práctica para hoy en casa</a></aside>`;highlights.insertAdjacentElement('afterend',box)}
const geo=document.getElementById('geografia');if(geo&&!geo.querySelector('.geo-visual')){const h2=geo.querySelector('h2');const fig=document.createElement('figure');fig.className='geo-visual';fig.innerHTML=`<img loading="lazy" src="https://commons.wikimedia.org/wiki/Special:FilePath/Tectonic%20plates%20around%20Japan.png" alt="Mapa de las placas tectónicas alrededor de Japón"><figcaption>Mapa de las principales placas tectónicas alrededor de Japón · Wikimedia Commons, CC BY-SA 2.5.</figcaption>`;h2?.insertAdjacentElement('afterend',fig);const prompt=document.createElement('div');prompt.className='look-first';prompt.innerHTML='<b>Míralo 20 segundos antes de seguir.</b>Localiza Japón, la placa del Pacífico al este y la del Mar de Filipinas al sur. Después pregúntate: ¿por qué un archipiélago situado justo en estas fronteras tendría tantos terremotos, fosas y volcanes?';fig.insertAdjacentElement('afterend',prompt)}
const art=document.getElementById('arte');if(art&&!art.querySelector('.look-first')){const lf=document.createElement('div');lf.className='look-first';lf.innerHTML='<b>Primera mirada · sin leer.</b>Mira la imagen durante 15 segundos. ¿Qué ves primero: la ola, el Fuji o las barcas? Solo después continúa con la explicación.';art.querySelector('.art-figure')?.insertAdjacentElement('beforebegin',lf)}
const music=document.getElementById('musica');if(music&&!music.querySelector('.look-first')){const lf=document.createElement('div');lf.className='look-first';lf.innerHTML='<b>Regla de esta ruta:</b> primero escucha, luego formula una pregunta, después lee la explicación y vuelve a escuchar. La música se aprende con el oído, no solo con texto.';music.querySelector('h2')?.insertAdjacentElement('afterend',lf)}
